apiVersion: projectsame.io/v1alpha1
metadata:
    name: ExternalDataSource
    version: 0.0.4
pipeline:
    name: "Using an Exetrnal Data Source"
    description: "A simple kubeflow execution designed to show using an external data source."
    package: "external_datasource.py"
run:
    name: "Using an Exetrnal Data Source"
    parameters:
        epochs: 10
        train_data_url: 
        test_data_url:
